[package]
name = "ofin-std"
version = "0.0.1"
authors = ["Nigecat"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
ofin-types = { path = "ofin-types" }
ofin-std-common = { path = "ofin-std-common" }