[package]
name = "ofin"
version = "0.0.1"
description = "A hotkey scripting language"
authors = ["Nigecat"]
edition = "2018"

[dependencies]
tracing-subscriber = "0.2.16"
tracing = { version = "0.1.25", features = ["log"] }
