[package]
name = "ofin"
version = "0.0.1"
authors = ["Nigecat"]
edition = "2018"

[dependencies]
log = "0.4.11"
thiserror = "1.0.22"
fancy-regex = "0.4.1"
pretty_env_logger = "0.4.0"
ofin-std = { path = "../ofin-std" }