name: Clippy check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features